Repository TeamFair/ILSANG-iOS, pull requests merged in 2024-07, with the labels that each got.

#59 [Feat/#47] Customer 정보, 경험치 API 연결
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Sources/Model/User.swift
  ILSANG/Sources/Model/XP.swift
  ILSANG/Sources/Network/UserNetwork.swift
  ILSANG/Sources/Network/XPNetwork.swift
  ILSANG/Sources/Views/ILSANGApp.swift
  ILSANG/Sources/Views/MyPage/MyPageProfile.swift
  ILSANG/Sources/Views/MyPage/MyPageView.swift
  ILSANG/Sources/Views/MyPage/MypageViewModel.swift
  ILSANG/Sources/Views/NickName/ChangeNickNameView.swift
Labels: Feat

#61 [Design/#60] 로그아웃, 회원탈퇴 알럿 구현 + 로고변경
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Resources/Assets.xcassets/Image/logo.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/logo.imageset/logo.svg
  ILSANG/Resources/Assets.xcassets/Logo/LoginLogo.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Logo/LoginLogo.imageset/LoginLogo.svg
  ILSANG/Resources/Launch Screen.storyboard
  ILSANG/Sources/Views/Approval/ApprovalView.swift
  ILSANG/Sources/Views/Login/LoginView.swift
  ILSANG/Sources/Views/NickName/ChangeNickNameView.swift
  ILSANG/Sources/Views/Setting/DeleteAccountView.swift
  ILSANG/Sources/Views/Setting/SettingAlertView.swift
  ILSANG/Sources/Views/Setting/SettingView.swift
Labels: Design

#66 [Bug/#65] 에러 픽스 - Customer > User 미변경된 부분, SubmitAlertView pbxproj에서 삭제
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Resources/Assets.xcassets/Image/logo.imageset/Contents.json
  ILSANG/Resources/Launch Screen.storyboard
  ILSANG/Sources/Views/Approval/ApprovalView.swift
  ILSANG/Sources/Views/MyPage/MyPageProfile.swift
  ILSANG/Sources/Views/MyPage/MypageViewModel.swift
Labels: Bug

#70 [Feat/#69] 도전내역 등록 API 연결
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Sources/Global/Model/Quest.swift
  ILSANG/Sources/Network/Base/APIManager.swift
  ILSANG/Sources/Network/Base/CommonResponse.swift
  ILSANG/Sources/Network/Base/Network.swift
  ILSANG/Sources/Network/Base/NetworkError.swift
  ILSANG/Sources/Network/ChallengeNetwork.swift
  ILSANG/Sources/Views/Quest/Submit/SubmitAlertViewModel.swift
  ILSANG/Sources/Views/Quest/Submit/SubmitRouterView.swift
Labels: Feat

#68 [Chore/#63] 다크모드 고정, 앱 아이콘 변경
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  ILSANG/Resources/Assets.xcassets/AppIcon.appiconset/ilsang-appicon.png
  ILSANG/Resources/Assets.xcassets/AppIcon.appiconset/ilsang-logo.png
Labels: Chore

#67 [Design/#64] 엣지케이스를 위한 ErrorView 생성
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Sources/Global/View/ErrorView.swift
  ILSANG/Sources/Views/Approval/ApprovalView.swift
  ILSANG/Sources/Views/Approval/ApprovalViewModel.swift
Labels: Design

#72 [Design/#71] 마이탭 디테일 수정
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Sources/Views/MyPage/MyPageProfile.swift
  ILSANG/Sources/Views/MyPage/MyPageSegmenet.swift
  ILSANG/Sources/Views/MyPage/MyPageView.swift
  ILSANG/Sources/Views/NickName/ChangeNickNameView.swift
  ILSANG/Sources/Views/Setting/TermsAndPolicyView.swift
Labels: Design

#73 [Feature/#62] 퀘스트 목록 조회 API 연결(완료/미완료)
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Sources/Model/Quest.swift
  ILSANG/Sources/Network/QuestNetwork.swift
  ILSANG/Sources/Views/MyPage/MyPageProfile.swift
  ILSANG/Sources/Views/MyPage/MyPageView.swift
  ILSANG/Sources/Views/MyPage/MypageViewModel.swift
Labels: Feat

#77 [Design/#75] 디자인 디테일 적용
  ILSANG/Sources/Component/Buttons.swift
  ILSANG/Sources/Global/Model/Setting.swift
  ILSANG/Sources/Global/View/ErrorView.swift
  ILSANG/Sources/Views/Approval/ApprovalView.swift
  ILSANG/Sources/Views/MyPage/MyPageList.swift
  ILSANG/Sources/Views/MyPage/MyPageProfile.swift
  ILSANG/Sources/Views/MyPage/MyPageSegmenet.swift
  ILSANG/Sources/Views/MyPage/MyPageView.swift
  ILSANG/Sources/Views/NickName/ChangeNickNameView.swift
  ILSANG/Sources/Views/Quest/QuestItemView.swift
  ILSANG/Sources/Views/Quest/QuestView.swift
  ILSANG/Sources/Views/Setting/CustomerServiceView.swift
  ILSANG/Sources/Views/Setting/DeleteAccountView.swift
  ILSANG/Sources/Views/Setting/SettingAlertView.swift
  ILSANG/Sources/Views/Setting/SettingView.swift
  ILSANG/Sources/Views/Setting/TermsAndPolicyView.swift
Labels: Design

#78 [Feat/#76] 7/3 API 서버 1.0.9-2 업데이트에 따른 수정 및 기존 에러 수정
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Sources/Extension/Dictionary++.swift
  ILSANG/Sources/Extension/String++.swift
  ILSANG/Sources/Model/Challenge.swift
  ILSANG/Sources/Model/Emoji.swift
  ILSANG/Sources/Model/User.swift
  ILSANG/Sources/Network/Base/APIManager.swift
  ILSANG/Sources/Network/ChallengeNetwork.swift
  ILSANG/Sources/Network/EmojiNetwork.swift
  ILSANG/Sources/Network/UserNetwork.swift
  ILSANG/Sources/Views/Approval/ApprovalViewModel.swift
Labels: Feat

#80 [Feat/#79] Quest 파일 수정, 인증탭 챌린지없을 때 이모지 조회 안하도록 수정 #79
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Sources/Model/Challenge.swift
  ILSANG/Sources/Model/Quest.swift
  ILSANG/Sources/Network/QuestNetwork.swift
  ILSANG/Sources/Views/Approval/ApprovalViewModel.swift
  ILSANG/Sources/Views/MyPage/MyPageView.swift
  ILSANG/Sources/Views/MyPage/MypageViewModel.swift
Labels: Feat

#82 [Feat] 경험치 API 연동
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Sources/Network/XPNetwork.swift
  ILSANG/Sources/Views/MyPage/MyPageProfile.swift
  ILSANG/Sources/Views/MyPage/MyPageView.swift
  ILSANG/Sources/Views/MyPage/MypageViewModel.swift
Labels: Feat

#83 [Feat/#81] 애플 로그인 구현, 로그인 API 연결
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/ILSANG.entitlements
  ILSANG/Sources/Global/Model/AuthChannel.swift
  ILSANG/Sources/Model/AuthUser.swift
  ILSANG/Sources/Network/AuthNetwork.swift
  ILSANG/Sources/Network/Base/Network.swift
  ILSANG/Sources/Service/AuthService.swift
  ILSANG/Sources/Service/UserService.swift
  ILSANG/Sources/Views/ILSANGApp.swift
  ILSANG/Sources/Views/Login/AppleLoginButtonView.swift
  ILSANG/Sources/Views/Login/GoogleLoginButtonView.swift
  ILSANG/Sources/Views/Login/LoginView.swift
  ILSANG/Sources/Views/Login/LoginViewModel.swift
  ILSANG/Sources/Views/Setting/SettingView.swift
Labels: Feat

#87 [Feat/#85] 완료/미완료 퀘스트 조회 API 통신 구현 및 QuestViewModel 구현
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Sources/Component/IconView.swift
  ILSANG/Sources/Global/Model/Quest.swift
  ILSANG/Sources/Model/Quest.swift
  ILSANG/Sources/Network/QuestNetwork.swift
  ILSANG/Sources/Views/Quest/QuestItemView.swift
  ILSANG/Sources/Views/Quest/QuestView.swift
  ILSANG/Sources/Views/Quest/QuestViewModel.swift
  ILSANG/Sources/Views/Quest/QuestViewModelItem.swift
Labels: Feat

#86 [Feat/#84] 마이탭 화면 대응 구현
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Sources/Extension/String++.swift
  ILSANG/Sources/Global/View/NavigationTitleView.swift
  ILSANG/Sources/Model/Challenge.swift
  ILSANG/Sources/Model/XP.swift
  ILSANG/Sources/Network/XPNetwork.swift
  ILSANG/Sources/Views/MyPage/MyPageActiveList.swift
  ILSANG/Sources/Views/MyPage/MyPageBadgeList.swift
  ILSANG/Sources/Views/MyPage/MyPageList.swift
  ILSANG/Sources/Views/MyPage/MyPageProfile.swift
  ILSANG/Sources/Views/MyPage/MyPageQuestList.swift
  ILSANG/Sources/Views/MyPage/MyPageView.swift
  ILSANG/Sources/Views/MyPage/MypageViewModel.swift
  ILSANG/Sources/Views/Quest/DetailQuestview.swift
Labels: Feat

#91 [Feat/#88] 도전내역 등록 시 퀘스트 목록 업데이트
  ILSANG/Sources/Views/Quest/QuestViewModel.swift
Labels: Feat

#90 [Feat/#89] 도전내역 구조체 수정 및 사용 뷰 수정, 에러뷰 수정
  ILSANG.xcodeproj/project.pbxproj
  ILSANG.xcodeproj/xcshareddata/xcschemes/ILSANG.xcscheme
  ILSANG/Sources/Model/Challenge.swift
  ILSANG/Sources/Views/Approval/ApprovalViewModel.swift
  ILSANG/Sources/Views/MyPage/MyPageQuestList.swift
  ILSANG/Sources/Views/MyPage/MyPageView.swift
  ILSANG/Sources/Views/Quest/DetailQuestview.swift
  ILSANG/Sources/Views/Quest/QuestView.swift
Labels: Feat
