Repository TeamFair/ILSANG-iOS, pull requests merged in 2024-11, with the labels that each got.

#188 [Design/#187] 탭바 아이콘 에셋 변경 (색상 및 랭킹 아이콘 변경 대응)
  ILSANG/Resources/Assets.xcassets/Image/Tab/approval.circle.fill.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Tab/approval.circle.fill.imageset/Quest.fill.pdf
  ILSANG/Resources/Assets.xcassets/Image/Tab/approval.circle.fill.imageset/approval.circle.fill.svg
  ILSANG/Resources/Assets.xcassets/Image/Tab/approval.circle.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Tab/approval.circle.imageset/Quest.pdf
  ILSANG/Resources/Assets.xcassets/Image/Tab/approval.circle.imageset/approval.circle.svg
  ILSANG/Resources/Assets.xcassets/Image/Tab/profile.fill.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Tab/profile.fill.imageset/Profile.fill.pdf
  ILSANG/Resources/Assets.xcassets/Image/Tab/profile.fill.imageset/profile.fill.svg
  ILSANG/Resources/Assets.xcassets/Image/Tab/profile.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Tab/profile.imageset/Profile.pdf
  ILSANG/Resources/Assets.xcassets/Image/Tab/profile.imageset/profile.svg
  ILSANG/Resources/Assets.xcassets/Image/Tab/quest.fill.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Tab/quest.fill.imageset/Receipt.fill.pdf
  ILSANG/Resources/Assets.xcassets/Image/Tab/quest.fill.imageset/quest.fill.svg
  ILSANG/Resources/Assets.xcassets/Image/Tab/quest.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Tab/quest.imageset/Receipt.pdf
  ILSANG/Resources/Assets.xcassets/Image/Tab/quest.imageset/quest.svg
  ILSANG/Resources/Assets.xcassets/Image/Tab/rank.fill.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Tab/rank.fill.imageset/Group.pdf
  ILSANG/Resources/Assets.xcassets/Image/Tab/rank.fill.imageset/trophy.fill 2.pdf
  ILSANG/Resources/Assets.xcassets/Image/Tab/rank.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Tab/rank.imageset/Group_fif.pdf
  ILSANG/Resources/Assets.xcassets/Image/Tab/rank.imageset/trophy.fill 1.pdf
Labels: Design

#192 [Design/#191] 퀘스트 목록 디자인 수정 (스탯 표기, 아이콘 변경)
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Resources/Assets.xcassets/Image/arrow-right.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/arrow-right.imageset/Vector 5.pdf
  ILSANG/Sources/Global/View/IconView.swift
  ILSANG/Sources/Global/View/TagView.swift
  ILSANG/Sources/Views/Quest/QuestItemView.swift
  ILSANG/Sources/Views/Quest/QuestView.swift
  ILSANG/Sources/Views/Quest/QuestViewModelItem.swift
Labels: Design

#195 [Chore/#194] 버전 1.2.2 배포 관련 수정
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Resources/XCConfig/Staging.xcconfig
  ILSANG/Sources/Views/Setting/SettingView.swift
Labels: Chore

#199 [ Feat/#193] 미완료 퀘스트 정렬 기능 추가
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Sources/Global/View/FilterPicker.swift
  ILSANG/Sources/Model/Quest.swift
  ILSANG/Sources/Views/Quest/QuestView.swift
  ILSANG/Sources/Views/Quest/QuestViewModel.swift
  ILSANG/Sources/Views/Quest/QuestViewModelItem.swift
Labels: Feat

#201 [Design/#200] 퀘스트 상세정보 시트 디자인 수정사항 반영
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Sources/Views/Quest/QuestDetailView.swift
  ILSANG/Sources/Views/Quest/QuestView.swift
Labels: Design

#196 [Feat/#186] 마이페이지 오각형 그래프 구현
  ILSANG.xcodeproj/project.pbxproj
  ILSANG.xcodeproj/xcshareddata/xcschemes/ILSANG.xcscheme
  ILSANG/Resources/Assets.xcassets/Image/profileEdit.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/profileEdit.imageset/profileEdit.svg
  ILSANG/Sources/Global/View/Polygon.swift
  ILSANG/Sources/Views/MyPage/MyPageBadgeList.swift
  ILSANG/Sources/Views/MyPage/MyPageProfile.swift
  ILSANG/Sources/Views/MyPage/MyPageSegmenet.swift
  ILSANG/Sources/Views/MyPage/MyPageView.swift
  ILSANG/Sources/Views/MyPage/MypageShareImage.swift
  ILSANG/Sources/Views/MyPage/MypageViewModel.swift
Labels: Feat

#203 [Feat/#202] 텍스트가 임의로 줄바꿈 되는 현상 방지하기 위한 프로퍼티 추가 (forceCharWrapping)
  ILSANG/Sources/Extension/String++.swift
  ILSANG/Sources/Views/Quest/QuestDetailView.swift
  ILSANG/Sources/Views/Quest/QuestItemView.swift
Labels: Feat
