Repository TeamFair/ILSANG-iOS, pull requests merged in 2024-09, with the labels that each got.

#134 [Feat/#133] 활동로그 url 변경 ( xp >> xpHistory )
  ILSANG/Sources/Network/XPNetwork.swift
Labels: Feat

#140 [Fix/#135] 삭제가 완료/미완료시 마이탭으로 돌아오도록 변경
  ILSANG/Sources/Views/Quest/DetailQuestview.swift
Labels: Bug

#138 [Feat/#137] 로그아웃, 회원탈퇴 로직 수정 (응답 구조 변경, 성공 시 로그인뷰로 화면 전환)
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Sources/Model/Logout.swift
  ILSANG/Sources/Model/Withdraw.swift
  ILSANG/Sources/Network/LogoutNetwork.swift
  ILSANG/Sources/Network/WithdrawNetwork.swift
  ILSANG/Sources/Service/UserService.swift
  ILSANG/Sources/Views/Setting/DeleteAccountView.swift
  ILSANG/Sources/Views/Setting/SettingView.swift
Labels: Feat

#143 [Chore/#142] 파일 위치 수정
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Sources/Extension/Color.swift
  ILSANG/Sources/Global/Model/Icon.swift
  ILSANG/Sources/Global/View/Buttons.swift
  ILSANG/Sources/Global/View/IconView.swift
  ILSANG/Sources/Views/MyPage/MypageViewModel.swift
  ILSANG/Sources/Views/Quest/QuestItemView.swift
  ILSANG/Sources/Views/Quest/QuestViewModel.swift
  ILSANG/Sources/Views/Quest/QuestViewModelItem.swift
Labels: Chore

#145 [Ref/#144] 도전내역 상태변경 API 엔드포인트 수정 (report >> status)
  ILSANG/Sources/Network/ChallengeNetwork.swift
Labels: Ref

#147 [Design/#146] 퀘스트뷰 상단 스탯 선택 영역 디자인 구현
  ILSANG/Sources/Views/Quest/QuestView.swift
  ILSANG/Sources/Views/Quest/QuestViewModel.swift
  ILSANG/Sources/Views/Quest/QuestViewModelItem.swift
Labels: Feat

#154 [Ref/#153] Challenge 구조체 필드 변경(quest 삭제, missionTitle 추가) 및 관련 로직 수정
  ILSANG/Sources/Model/Challenge.swift
  ILSANG/Sources/Views/Approval/ApprovalViewModel.swift
  ILSANG/Sources/Views/MyPage/MyPageQuestList.swift
  ILSANG/Sources/Views/Quest/DetailQuestview.swift
Labels: Ref

#152 [Feat/#151] 미완료 퀘스트의 XpStat별 분류 로직 추가 및 페이지네이션 로직 리팩토링
  ILSANG/Sources/Views/Quest/QuestView.swift
  ILSANG/Sources/Views/Quest/QuestViewModel.swift
Labels: Feat

#155 [Feat/#149] 마이 탭 5가지 스텟 표 구현
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Sources/Model/XpStats.swift
  ILSANG/Sources/Network/XPNetwork.swift
  ILSANG/Sources/Views/MyPage/MyPageActiveList.swift
  ILSANG/Sources/Views/MyPage/MyPageProfile.swift
  ILSANG/Sources/Views/MyPage/MyPageQuestList.swift
  ILSANG/Sources/Views/MyPage/MyPageView.swift
  ILSANG/Sources/Views/MyPage/MypageViewModel.swift
  ILSANG/Sources/Views/Quest/DetailQuestview.swift
Labels: Feat
