Repository TeamFair/ILSANG-iOS, pull requests merged in 2024-05, with the labels that each got.

#8 [Chore/#7] 초기 깃 세팅
  .gitattributes
  .gitignore
Labels: Chore

#10 [Chore/#9] 프로젝트 생성
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  ILSANG/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  ILSANG/Resources/Assets.xcassets/Contents.json
  ILSANG/Resources/Launch Screen.storyboard
  ILSANG/Resources/Preview Content/Preview Assets.xcassets/Contents.json
  ILSANG/Sources/ContentView.swift
  ILSANG/Sources/ILSANGApp.swift
  ILSANGTests/ILSANGTests.swift
  ILSANGUITests/ILSANGUITests.swift
  ILSANGUITests/ILSANGUITestsLaunchTests.swift
Labels: Chore

#17 [Design/#16] QuestView 레이아웃 구현
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Resources/Assets.xcassets/Color/Main/PrimaryPurple.colorset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/arrow-down.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/arrow-down.imageset/arrow-down.svg
  ILSANG/Resources/Assets.xcassets/Image/check.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/check.imageset/check.svg
  ILSANG/Sources/Global/Component/IconView.swift
  ILSANG/Sources/Global/Model/Quest.swift
  ILSANG/Sources/Views/Quest/QuestItemView.swift
  ILSANG/Sources/Views/Quest/QuestView.swift
  ILSANG/Sources/Views/Quest/QuestViewModel.swift
Labels: Design

#20 [Feat/#15] 마이페이지 구현
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Sources/Component/Buttons.swift
  ILSANG/Sources/Global/Model/UserData.swift
  ILSANG/Sources/Views/MyPage/MyPageList.swift
  ILSANG/Sources/Views/MyPage/MyPageProfile.swift
  ILSANG/Sources/Views/MyPage/MyPageSegmenet.swift
  ILSANG/Sources/Views/MyPage/MyPageView.swift
Labels: Feat

#19 [Design/#18] 퀘스트 제출 Alert 디자인 구현
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Resources/Assets.xcassets/Color/Sub/SubBlue.colorset/Contents.json
  ILSANG/Resources/Assets.xcassets/Color/Sub/SubGreen.colorset/Contents.json
  ILSANG/Resources/Assets.xcassets/Color/Sub/SubRed.colorset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/ellipsis.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/ellipsis.imageset/ellipsis.svg
  ILSANG/Resources/Assets.xcassets/Image/xmark.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/xmark.imageset/xmark.pdf
  ILSANG/Sources/Component/Buttons.swift
  ILSANG/Sources/Component/IconView.swift
  ILSANG/Sources/Views/Quest/QuestItemView.swift
  ILSANG/Sources/Views/Quest/SubmitAlertView.swift
Labels: Design
