Repository TeamFair/ILSANG-iOS, pull requests merged in 2024-12, with the labels that each got.

#206 [Bug/#205] 오각형 그래프 버그 수정
  ILSANG/Sources/Global/View/Polygon.swift
  ILSANG/Sources/Views/MyPage/MyPageBadgeList.swift
  ILSANG/Sources/Views/MyPage/MypageShareImage.swift
Labels: Bug

#210 [Chore/#209] 1.2.3 마케팅 버전 수정, 컴파일 에러 수정, 스탯라벨 중복 제거
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Sources/Views/MyPage/MyPageBadgeList.swift
  ILSANG/Sources/Views/MyPage/MypageShareImage.swift
  ILSANG/Sources/Views/Quest/QuestView.swift
  ILSANG/Sources/Views/Setting/SettingView.swift
Labels: Chore

#207 [Feat/#204] 반복퀘스트 기능 & UI 구현
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Resources/Assets.xcassets/Color/Badge/Contents.json
  ILSANG/Resources/Assets.xcassets/Color/Badge/Fg_Badge_green_.colorset/Contents.json
  ILSANG/Resources/Assets.xcassets/Color/Badge/Gradient/Contents.json
  ILSANG/Resources/Assets.xcassets/Color/Badge/Gradient/Daily_Left.colorset/Contents.json
  ILSANG/Resources/Assets.xcassets/Color/Badge/Gradient/Daily_Right.colorset/Contents.json
  ILSANG/Resources/Assets.xcassets/Color/Badge/Gradient/Monthly_Left.colorset/Contents.json
  ILSANG/Resources/Assets.xcassets/Color/Badge/Gradient/Monthly_Right.colorset/Contents.json
  ILSANG/Resources/Assets.xcassets/Color/Badge/Gradient/Weekly_Left.colorset/Contents.json
  ILSANG/Resources/Assets.xcassets/Color/Badge/Gradient/Weekly_Right.colorset/Contents.json
  ILSANG/Resources/XCConfig/Staging.xcconfig
  ILSANG/Sources/Enum/QuestStatus.swift
  ILSANG/Sources/Enum/RepeatType.swift
  ILSANG/Sources/Enum/XpStat.swift
  ILSANG/Sources/Global/View/FilterPicker.swift
  ILSANG/Sources/Global/View/TagView.swift
  ILSANG/Sources/Network/Base/Network.swift
  ILSANG/Sources/Network/QuestNetwork.swift
  ILSANG/Sources/Views/Quest/Component/QuestImageWithTagView.swift
  ILSANG/Sources/Views/Quest/Component/StatGridView.swift
  ILSANG/Sources/Views/Quest/QuestItemView.swift
  ILSANG/Sources/Views/Quest/QuestView.swift
  ILSANG/Sources/Views/Quest/QuestViewModel.swift
  ILSANG/Sources/Views/Quest/QuestViewModelItem.swift
Labels: Feat

#212 [Ref/#208] 사용하지 않는 레거시 모델 제거
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Sources/Global/Model/UserData.swift
  ILSANG/Sources/Global/Model/XpStat.swift
  ILSANG/Sources/Global/View/Polygon.swift
  ILSANG/Sources/Model/Challenge.swift
  ILSANG/Sources/Model/Quest.swift
  ILSANG/Sources/Model/Rank.swift
  ILSANG/Sources/Model/User.swift
  ILSANG/Sources/Model/XP.swift
  ILSANG/Sources/Model/XpLog.swift
  ILSANG/Sources/Model/XpStats.swift
  ILSANG/Sources/Network/UserNetwork.swift
  ILSANG/Sources/Network/XPNetwork.swift
  ILSANG/Sources/Views/MyPage/MyPageActiveList.swift
  ILSANG/Sources/Views/MyPage/MyPageView.swift
  ILSANG/Sources/Views/MyPage/MypageViewModel.swift
Labels: Ref

#213 [Ref/#208] 기존 XpStat 파일 제거
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Sources/Global/Model/XpStat.swift
Labels: Ref

#216 [Design/#215] 로그인 UI 수정 (슬라이드 추가, 애플 버튼 디자인 수정)
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Resources/Assets.xcassets/Color/Main/SecondaryGreen.colorset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Slide/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Slide/slide0.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Slide/slide0.imageset/slide0.pdf
  ILSANG/Resources/Assets.xcassets/Image/Slide/slide1.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Slide/slide1.imageset/slide1.pdf
  ILSANG/Resources/Assets.xcassets/Image/Slide/slide2.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Slide/slide2.imageset/slide2.pdf
  ILSANG/Sources/Enum/XpStat.swift
  ILSANG/Sources/Extension/CGFloat++.swift
  ILSANG/Sources/Global/View/CarouselAutoSlideView.swift
  ILSANG/Sources/Views/Login/AppleLoginButtonView.swift
  ILSANG/Sources/Views/Login/LoginView.swift
Labels: Design

#217 [Design/#214] 홈 탭 UI 추가
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Resources/Assets.xcassets/Image/Tab/home.fill.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Tab/home.fill.imageset/home.fill.pdf
  ILSANG/Resources/Assets.xcassets/Image/Tab/home.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Tab/home.imageset/home.pdf
  ILSANG/Resources/Assets.xcassets/Logo/logo.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Logo/logo.imageset/logo.svg
  ILSANG/Resources/Assets.xcassets/Logo/logoWithAlpha.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Logo/logoWithAlpha.imageset/logo.pdf
  ILSANG/Sources/Enum/XpStat.swift
  ILSANG/Sources/Model/Quest.swift
  ILSANG/Sources/Views/Home/HomeView.swift
  ILSANG/Sources/Views/Home/HomeViewModel.swift
  ILSANG/Sources/Views/Home/TitleWithContentView.swift
  ILSANG/Sources/Views/Quest/Component/QuestImageWithTagView.swift
  ILSANG/Sources/Views/Quest/Component/StatGridView.swift
  ILSANG/Sources/Views/Quest/Component/StatHeaderView.swift
  ILSANG/Sources/Views/Quest/QuestItemView.swift
  ILSANG/Sources/Views/Quest/QuestStyle.swift
  ILSANG/Sources/Views/Quest/QuestView.swift
  ILSANG/Sources/Views/Quest/QuestViewModel.swift
  ILSANG/Sources/Views/Quest/QuestViewModelItem.swift
  ILSANG/Sources/Views/Ranking/RankingItemView.swift
  ILSANG/Sources/Views/Ranking/RankingView.swift
  ILSANG/Sources/Views/Router/MainTabView.swift
  ILSANG/Sources/Views/Router/Tab.swift
Labels: Design
