Repository TeamFair/ILSANG-iOS, pull requests merged in 2024-08, with the labels that each got.

#94 [Bug/#93] 애플로그인 성공 시 userEmail에 애플 이메일 할당
  ILSANG/Sources/Service/UserService.swift
Labels: Bug

#95 [Fix/#92] 날짜 표기 개선
  ILSANG/Sources/Extension/String++.swift
  ILSANG/Sources/Views/MyPage/MyPageQuestList.swift
  ILSANG/Sources/Views/Quest/DetailQuestview.swift
Labels: Bug

#100 [Feat/#99] DEBUG일 때만 카카오, 구글 로그인 버튼 활성화하도록 구현
  ILSANG/Sources/Views/Login/LoginView.swift
  ILSANG/Sources/Views/Login/LoginViewModel.swift
Labels: Feat

#98 [Design/#97] 탭바 디자인 불일치 수정(기본 Appearance 지정, 배경 흰색 고정)
  ILSANG/Sources/Views/ILSANGApp.swift
Labels: Design

#101 [Bug/#96] XP 표시와 다르게 오르는 현상, 프로그레스 바 수치 불일치
  ILSANG/Sources/Views/MyPage/MyPageProfile.swift
  ILSANG/Sources/Views/MyPage/MypageViewModel.swift
Labels: Bug

#104 [Bug/#103]활동탭 데이터가 보이지 않음
  ILSANG/Sources/Extension/String++.swift
  ILSANG/Sources/Model/XP.swift
  ILSANG/Sources/Network/XPNetwork.swift
  ILSANG/Sources/Views/MyPage/MyPageActiveList.swift
  ILSANG/Sources/Views/MyPage/MyPageBadgeList.swift
  ILSANG/Sources/Views/MyPage/MyPageView.swift
  ILSANG/Sources/Views/MyPage/MypageViewModel.swift
Labels: Bug

#108 [Design/#105] 퀘스트 이미지 레이아웃(사이즈) 수정
  ILSANG/Sources/Views/Quest/QuestItemView.swift
  ILSANG/Sources/Views/Quest/QuestView.swift
Labels: Design

#107 [Feat/#105] 퀘스트뷰 - 중복된 퀘스트 제거 로직 추가
  ILSANG/Sources/Views/Quest/QuestViewModel.swift
Labels: Feat

#106 [Feat/#102] 도전내역 랜덤조회 응답 구조 변경
  ILSANG/Sources/Model/Challenge.swift
  ILSANG/Sources/Network/ChallengeNetwork.swift
  ILSANG/Sources/Views/Approval/ApprovalViewModel.swift
  ILSANG/Sources/Views/MyPage/MyPageQuestList.swift
  ILSANG/Sources/Views/Quest/DetailQuestview.swift
Labels: Feat

#112 [Bug/#111] 인증뷰 데이터 조회시 인덱스 초기화, 랜덤도전내역 조회 사이즈 20 지정
  ILSANG/Sources/Views/Approval/ApprovalViewModel.swift
Labels: Bug

#118 [Feat/#117] 이미지 등록 로직 수정(이미지 사이즈에 따라 다운샘플링 수치 조정, 100kb 미만일 때까지 JPEG 압축)
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Sources/Extension/Data++.swift
  ILSANG/Sources/Network/Base/Network.swift
Labels: Feat

#116 [Design/#115] 인증탭 기본이미지 수정
  ILSANG/Sources/Views/Approval/ApprovalView.swift
Labels: Design

#120 [Chore/#119] 앱 이름, 마케팅버전 변경(1.0.1)
  ILSANG.xcodeproj/project.pbxproj
Labels: Chore

#122 [Feat/#117] 이미지 POST 시 파일 크기 초과에 대응하도록 로직 수정
  ILSANG/Sources/Extension/UIImage++.swift
  ILSANG/Sources/Network/Base/Network.swift
Labels: Feat

#125 [Bug/#124] 퀘스트 이미지 꼬임 현상 해결
  ILSANG/Sources/Views/Quest/QuestViewModel.swift
Labels: Bug

#126 [Feat/#123] 도전내역 신고 디자인&기능 구현
  ILSANG/Sources/Network/ChallengeNetwork.swift
  ILSANG/Sources/Views/Approval/ApprovalView.swift
  ILSANG/Sources/Views/Approval/ApprovalViewModel.swift
  ILSANG/Sources/Views/Setting/SettingAlertView.swift
Labels: Feat

#121 [Feat/#114] 챌린지 삭제 기능 추가
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Sources/Global/View/NavigationTitleView.swift
  ILSANG/Sources/Network/ChallengeNetwork.swift
  ILSANG/Sources/Network/ImageNetwork.swift
  ILSANG/Sources/Views/MyPage/MyPageActiveList.swift
  ILSANG/Sources/Views/MyPage/MyPageProfile.swift
  ILSANG/Sources/Views/MyPage/MyPageQuestList.swift
  ILSANG/Sources/Views/MyPage/MyPageView.swift
  ILSANG/Sources/Views/MyPage/MypageViewModel.swift
  ILSANG/Sources/Views/Quest/DetailQuestview.swift
  ILSANG/Sources/Views/Setting/SettingAlertView.swift
Labels: Feat

#131 [Fix/#130] 경험치가 양수일때 + 음수일때 - Nil일때 +0
  ILSANG/Sources/Views/MyPage/MyPageQuestList.swift
Labels: Bug

#132 [Feat/#129] 퀘스트 빈 경우 데이터 로드 메서드 연결
  ILSANG/Sources/Views/Quest/QuestView.swift
Labels: Feat
