Repository TeamFair/ILSANG-iOS, pull requests merged in 2024-06, with the labels that each got.

#23 [Feat/#22] 카메라 촬영 기능 구현
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Sources/Extension/Image++.swift
  ILSANG/Sources/Extension/View++.swift
  ILSANG/Sources/Global/Model/Quest.swift
  ILSANG/Sources/Views/Quest/Camera/Camera.swift
  ILSANG/Sources/Views/Quest/Camera/CameraView.swift
  ILSANG/Sources/Views/Quest/Camera/CameraViewModel.swift
  ILSANG/Sources/Views/Quest/Camera/ImagePreviewButton.swift
  ILSANG/Sources/Views/Quest/QuestItemView.swift
  ILSANG/Sources/Views/Quest/QuestView.swift
  ILSANG/Sources/Views/Quest/QuestViewModel.swift
  ILSANG/Sources/Views/Quest/SubmitRouterView.swift
Labels: Feat

#28 [Design/#27] TabBarAppearance 수정 - 배경색상, 구분선 설정
  ILSANG/Sources/Views/ILSANGApp.swift
Labels: Design

#26 [Feat/#24] 인증뷰의 디자인 및 이미지 스크롤 기능 구현 (ApprovalView)
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Resources/Assets.xcassets/Color/Shadow/ShadowFF.colorset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/like.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/like.imageset/like@1x.png
  ILSANG/Resources/Assets.xcassets/Image/like.imageset/like@2x.png
  ILSANG/Resources/Assets.xcassets/Image/like.imageset/like@3x.png
  ILSANG/Resources/Assets.xcassets/Image/profile.circle.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/profile.circle.imageset/profile.pdf
  ILSANG/Resources/Assets.xcassets/Image/unlike.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/unlike.imageset/unlike@1x.png
  ILSANG/Resources/Assets.xcassets/Image/unlike.imageset/unlike@2x.png
  ILSANG/Resources/Assets.xcassets/Image/unlike.imageset/unlike@3x.png
  ILSANG/Resources/Assets.xcassets/img0.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/img0.imageset/img0.png
  ILSANG/Resources/Assets.xcassets/img1.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/img1.imageset/img1.png
  ILSANG/Resources/Assets.xcassets/img2.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/img2.imageset/img2.png
  ILSANG/Resources/Assets.xcassets/img3.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/img3.imageset/img3.png
  ILSANG/Sources/Views/Approval/ApprovalImageView.swift
  ILSANG/Sources/Views/Approval/ApprovalView.swift
  ILSANG/Sources/Views/Approval/ApprovalViewModel.swift
Labels: Feat

#32 [Feat/#25] 닉네임 변경 알림 추가
  ILSANG/Sources/Views/NickName/ChangeNickNameView.swift
Labels: Feat

#35 [Design/#34] 탭바 디자인 수정(에셋 적용, 아이템 여백 수정)
  ILSANG/Resources/Assets.xcassets/Image/Tab/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Tab/approval.circle.fill.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Tab/approval.circle.fill.imageset/approval.circle.fill.svg
  ILSANG/Resources/Assets.xcassets/Image/Tab/approval.circle.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Tab/approval.circle.imageset/approval.circle.svg
  ILSANG/Resources/Assets.xcassets/Image/Tab/profile.fill.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Tab/profile.fill.imageset/profile.fill.svg
  ILSANG/Resources/Assets.xcassets/Image/Tab/profile.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Tab/profile.imageset/profile.svg
  ILSANG/Resources/Assets.xcassets/Image/Tab/quest.fill.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Tab/quest.fill.imageset/quest.fill.svg
  ILSANG/Resources/Assets.xcassets/Image/Tab/quest.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Tab/quest.imageset/quest.svg
  ILSANG/Sources/Views/ILSANGApp.swift
  ILSANG/Sources/Views/Router/MainTabView.swift
  ILSANG/Sources/Views/Router/Tab.swift
Labels: Design

#39 [Design/#38] 앱 아이콘, 런치스크린, 로그인화면 디자인 수정
  ILSANG/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  ILSANG/Resources/Assets.xcassets/AppIcon.appiconset/ilsang-logo.png
  ILSANG/Resources/Assets.xcassets/Image/logo.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/logo.imageset/logo.svg
  ILSANG/Resources/Launch Screen.storyboard
  ILSANG/Sources/Views/Login/GoogleLoginButtonView.swift
  ILSANG/Sources/Views/Login/LoginView.swift
Labels: Design

#37 [Design/#36] 퀘스트/완료한 퀘스트 없을 경우 화면 디자인 적용
  ILSANG/Sources/Global/Model/Quest.swift
  ILSANG/Sources/Views/Quest/QuestItemView.swift
  ILSANG/Sources/Views/Quest/QuestView.swift
  ILSANG/Sources/Views/Quest/QuestViewModel.swift
Labels: Design

#43 [Design/#41] 마이페이지, 회원탈퇴 디테일/문구 수정
  ILSANG/Resources/Assets.xcassets/Image/Setting.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Setting.imageset/Setting.svg
  ILSANG/Resources/Assets.xcassets/Image/SettingPencil.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/SettingPencil.imageset/pencil.circle.fill@2x.png
  ILSANG/Sources/Views/MyPage/MyPageList.swift
  ILSANG/Sources/Views/MyPage/MyPageProfile.swift
  ILSANG/Sources/Views/MyPage/MyPageSegmenet.swift
  ILSANG/Sources/Views/MyPage/MyPageView.swift
  ILSANG/Sources/Views/Setting/DeleteAccountView.swift
Labels: Design

#44 [Chore/#40] 카메라, 앨범 접근 권한 문구 수정
  ILSANG.xcodeproj/project.pbxproj
Labels: Chore

#45 [Feat/#42] API 연결을 위한 Network 클래스 생성
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Sources/Model/Emoji.swift
  ILSANG/Sources/Network/Base/APIManager.swift
  ILSANG/Sources/Network/Base/APITarget.swift
  ILSANG/Sources/Network/Base/Network.swift
  ILSANG/Sources/Network/EmojiNetwork.swift
  ILSANG/Sources/Views/Approval/ApprovalView.swift
  ILSANG/Sources/Views/Approval/ApprovalViewModel.swift
Labels: Feat

#48 [Feat/#46] 이미지 조회 API 연결
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Sources/Network/Base/Network.swift
  ILSANG/Sources/Network/ImageNetwork.swift
  ILSANG/Sources/Views/Approval/ApprovalImageView.swift
  ILSANG/Sources/Views/Approval/ApprovalView.swift
  ILSANG/Sources/Views/Approval/ApprovalViewModel.swift
Labels: Feat

#52 [Feat/#51] 고객센터 인스타 연결, 이용약관 문서 변경
  ILSANG/Sources/Global/Model/Setting.swift
  ILSANG/Sources/Views/Setting/CustomerServiceView.swift
Labels: Feat

#54 [Feat/#50] 이모지 조회, 등록, 삭제 API 연결
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Resources/Assets.xcassets/Image/like.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/like.imageset/like@1x.png
  ILSANG/Resources/Assets.xcassets/Image/like.imageset/like@2x.png
  ILSANG/Resources/Assets.xcassets/Image/like.imageset/like@3x.png
  ILSANG/Resources/Assets.xcassets/Image/unlike.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/unlike.imageset/unlike@1x.png
  ILSANG/Resources/Assets.xcassets/Image/unlike.imageset/unlike@2x.png
  ILSANG/Resources/Assets.xcassets/Image/unlike.imageset/unlike@3x.png
  ILSANG/Sources/Model/Emoji.swift
  ILSANG/Sources/Network/Base/CommonResponse.swift
  ILSANG/Sources/Network/EmojiNetwork.swift
  ILSANG/Sources/Views/Approval/ApprovalView.swift
  ILSANG/Sources/Views/Approval/ApprovalViewModel.swift
Labels: Feat

#55 [Feat/#53] 로그아웃, 회원탈퇴 API 연동
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Sources/Model/Logout.swift
  ILSANG/Sources/Model/Withdraw.swift
  ILSANG/Sources/Network/LogoutNetwork.swift
  ILSANG/Sources/Network/WithdrawNetwork.swift
  ILSANG/Sources/Views/Setting/DeleteAccountView.swift
  ILSANG/Sources/Views/Setting/SettingView.swift
Labels: Feat

#56 [Feat/#49] 도전내역 조회, 도전내역 랜덤 조회 API 연결
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Sources/Model/Challenge.swift
  ILSANG/Sources/Network/ChallengeNetwork.swift
  ILSANG/Sources/Views/Approval/ApprovalView.swift
  ILSANG/Sources/Views/Approval/ApprovalViewModel.swift
Labels: Feat
