Repository TeamFair/ILSANG-iOS, pull requests merged in 2024-10, with the labels that each got.

#157 [Chore/#156] 1.1.0 배포 버전 수정
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Sources/Views/Quest/QuestView.swift
Labels: Chore

#159 [bug/#158] 레벨이 음수로 출력될때 예외 처리
  ILSANG/Sources/Views/MyPage/MypageViewModel.swift
Labels: Bug

#161 [Bug/#160] 미완료퀘스트 페이지네이션 & 스탯분리 로직 수정
  ILSANG/Sources/Network/QuestNetwork.swift
  ILSANG/Sources/Views/Quest/QuestView.swift
  ILSANG/Sources/Views/Quest/QuestViewModel.swift
Labels: Bug

#164 [Feat/#163] 랭킹시스템 UI 제작, Api 연동
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Resources/Assets.xcassets/Image/Tab/rank.fill.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Tab/rank.fill.imageset/rank.svg
  ILSANG/Resources/Assets.xcassets/Image/Tab/rank.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Tab/rank.imageset/trophy 4.svg
  ILSANG/Sources/Model/User.swift
  ILSANG/Sources/Network/UserNetwork.swift
  ILSANG/Sources/Views/Quest/QuestViewModelItem.swift
  ILSANG/Sources/Views/Ranking/RankingItemView.swift
  ILSANG/Sources/Views/Ranking/RankingView.swift
  ILSANG/Sources/Views/Ranking/RankingViewModel.swift
  ILSANG/Sources/Views/Router/MainTabView.swift
  ILSANG/Sources/Views/Router/Tab.swift
Labels: Feat

#168 [Design/#167] 랭킹탭 아이콘 에셋 수정
  ILSANG/Resources/Assets.xcassets/Image/Tab/rank.fill.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Tab/rank.fill.imageset/rank.svg
  ILSANG/Resources/Assets.xcassets/Image/Tab/rank.fill.imageset/trophy.fill 2.pdf
  ILSANG/Resources/Assets.xcassets/Image/Tab/rank.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Tab/rank.imageset/trophy 4.svg
  ILSANG/Resources/Assets.xcassets/Image/Tab/rank.imageset/trophy.fill 1.pdf
Labels: Design

#166 [Design/#165] 도전내역 디테일뷰 디자인 수정 & 공유하기 기능 구현
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Resources/Assets.xcassets/Image/heart.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/heart.imageset/heart.pdf
  ILSANG/Resources/Assets.xcassets/Image/more.vertical.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/more.vertical.imageset/more-vertical.pdf
  ILSANG/Resources/Assets.xcassets/Image/share.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/share.imageset/share.pdf
  ILSANG/Resources/Assets.xcassets/Image/trash.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/trash.imageset/trash-2.pdf
  ILSANG/Sources/Global/Model/TransferableUIImage.swift
  ILSANG/Sources/Model/Challenge.swift
  ILSANG/Sources/Views/MyPage/MyPageChallenge/ChallengeDetailView.swift
  ILSANG/Sources/Views/MyPage/MyPageChallenge/MyPageChallengeList.swift
  ILSANG/Sources/Views/MyPage/MyPageView.swift
  ILSANG/Sources/Views/Quest/DetailQuestview.swift
  ILSANG/Sources/Views/Setting/SettingAlertView.swift
Labels: Feat, Design

#171 [Ref/#170] 퀘스트 탭 throttle 적용, 뷰모델 초기화 시 데이터 불러오도록 로직 수정
  ILSANG/Sources/Views/Quest/QuestView.swift
  ILSANG/Sources/Views/Quest/QuestViewModel.swift
Labels: Ref

#173 [Ref/#172] 네트워크 관련 클래스 인스턴스 재생성 최소화 및 마이탭 뷰모델 최적화
  ILSANG/Sources/Model/XP.swift
  ILSANG/Sources/Network/ChallengeNetwork.swift
  ILSANG/Sources/Network/EmojiNetwork.swift
  ILSANG/Sources/Views/Approval/ApprovalView.swift
  ILSANG/Sources/Views/Approval/ApprovalViewModel.swift
  ILSANG/Sources/Views/MyPage/MyPageActiveList.swift
  ILSANG/Sources/Views/MyPage/MyPageBadgeList.swift
  ILSANG/Sources/Views/MyPage/MyPageChallenge/ChallengeDetailView.swift
  ILSANG/Sources/Views/MyPage/MyPageChallenge/MyPageChallengeList.swift
  ILSANG/Sources/Views/MyPage/MyPageProfile.swift
  ILSANG/Sources/Views/MyPage/MyPageSegmenet.swift
  ILSANG/Sources/Views/MyPage/MyPageView.swift
  ILSANG/Sources/Views/MyPage/MypageViewModel.swift
Labels: Ref

#177 [Bug/#176] 카메라 촬영 버튼 눌러도 제출화면으로 전환되지 않는 문제 해결
  ILSANG/Sources/Views/Quest/Camera/CameraView.swift
Labels: Bug

#175 [Design/#174] 도전내역 이미지 제출 완료 팝업창 수정
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Resources/Assets.xcassets/Image/Stat/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Stat/charm.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Stat/charm.imageset/heart.pdf
  ILSANG/Resources/Assets.xcassets/Image/Stat/fun.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Stat/fun.imageset/Frame 2405.pdf
  ILSANG/Resources/Assets.xcassets/Image/Stat/intellect.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Stat/intellect.imageset/Frame 2409.pdf
  ILSANG/Resources/Assets.xcassets/Image/Stat/sociability.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Stat/sociability.imageset/Frame 2407.pdf
  ILSANG/Resources/Assets.xcassets/Image/Stat/strength.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Stat/strength.imageset/Frame 2418.pdf
  ILSANG/Resources/Assets.xcassets/Image/arrow-up-effect.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/arrow-up-effect.imageset/success.pdf
  ILSANG/Resources/Assets.xcassets/Image/arrow-up.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/arrow-up.imageset/arrow-up.pdf
  ILSANG/Sources/Views/Quest/Camera/CameraView.swift
  ILSANG/Sources/Views/Quest/Camera/ImagePreviewButton.swift
  ILSANG/Sources/Views/Quest/QuestView.swift
  ILSANG/Sources/Views/Quest/QuestViewModelItem.swift
  ILSANG/Sources/Views/Quest/Submit/SubmitAlertView.swift
  ILSANG/Sources/Views/Quest/Submit/SubmitAlertViewModel.swift
  ILSANG/Sources/Views/Quest/Submit/SubmitRouterView.swift
  ILSANG/Sources/Views/Quest/Submit/SubmitRouterViewModel.swift
  ILSANG/Sources/Views/Quest/Submit/SubmitStatusView.swift
Labels: Design

#179 [Feat/#178] 퀘스트 스탯이 0이상일 경우에만 표시하도록 수정
  ILSANG/Sources/Views/Quest/QuestViewModelItem.swift
Labels: Feat

#181 [Chore/#180] 버전 1.2.1 배포 관련 수정 (마케팅 버전 수정, 기본 언어 수정, 세팅뷰 버전 수정)
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Sources/Views/Setting/SettingView.swift
Labels: Chore

#185 [Feat/#184] 닉네임 글자 수 제한
  ILSANG/Sources/Views/MyPage/MypageViewModel.swift
  ILSANG/Sources/Views/NickName/ChangeNickNameView.swift
Labels: Feat

#183 [Design/#182] 랭킹 탭 디자인 수정
  ILSANG.xcodeproj/project.pbxproj
  ILSANG/Resources/Assets.xcassets/Color/BackgroundBlue.colorset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Rank/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Rank/rank1.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Rank/rank1.imageset/Group 115937.pdf
  ILSANG/Resources/Assets.xcassets/Image/Rank/rank2.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Rank/rank2.imageset/Group 115937-1.pdf
  ILSANG/Resources/Assets.xcassets/Image/Rank/rank3.imageset/Contents.json
  ILSANG/Resources/Assets.xcassets/Image/Rank/rank3.imageset/Group 115937-2.pdf
  ILSANG/Sources/Extension/UIDevice++.swift
  ILSANG/Sources/Views/Ranking/RankingItemView.swift
  ILSANG/Sources/Views/Ranking/RankingView.swift
Labels: Design
